CRITICAL - 2022-12-13 00:04:38 --> Undefined variable: query_database_route24
in APPPATH\Libraries\post.php on line 32.
 1 APPPATH\Libraries\post.php(32): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: query_database_route24', 'APPPATH\\Libraries\\post.php', 32, [...])
 2 APPPATH\Controllers\influencer_controller.php(46): App\Libraries\post->postt('11081', 'facebook')
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-13 00:05:00 --> Undefined variable: strinfliencer_id
in APPPATH\Libraries\post.php on line 36.
 1 APPPATH\Libraries\post.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: strinfliencer_id', 'APPPATH\\Libraries\\post.php', 36, [...])
 2 APPPATH\Controllers\influencer_controller.php(46): App\Libraries\post->postt('11081', 'facebook')
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-13 01:08:19 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 in C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('192.168.11.24', 'intern', 'TVIw3yZchDLH', 'influencer', 3306, '', 0)
#1 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Project\system\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT facebook...')
#4 C:\xampp\htdocs\Project\app\Models\database24_.php(27): CodeIgniter\Model->__call('query', Array)
#5 C:\xampp\htdocs\Project\app\Controllers\influencer_controller.php(34): App\Models\database24_->query_24(NULL, NULL)
#6 C:\xampp\htdocs\Project\system\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
#7 C:\xampp\htdocs\Project\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
#8 C:\xampp\htdocs\Project\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Project\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 in C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Project\system\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT facebook...')
#3 C:\xampp\htdocs\Project\app\Models\database24_.php(27): CodeIgniter\Model->__call('query', Array)
#4 C:\xampp\htdocs\Project\app\Controllers\influencer_controller.php(34): App\Models\database24_->query_24(NULL, NULL)
#5 C:\xampp\htdocs\Project\system\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
#6 C:\xampp\htdocs\Project\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
#7 C:\xampp\htdocs\Project\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Project\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-13 01:08:19 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT facebook_engage_average,facebook_engage_rate,facebook_link,facebook_followed
        ,instagram_engage_average, instagram_engage_rate,instagram_link,instagram_followed_by
        ,twitter_engage_average,twitter_engage_rate,twitter_link,twitter_followers
        ,tiktok_engage_average,tiktok_engage_rate,tiktok_link,tiktok_followers
        FROM influencer WHERE   influencer_id = \'\'
        ORDER BY created_date DESC
        LIMIT 0, 1')
 3 APPPATH\Models\database24_.php(27): CodeIgniter\Model->__call('query', [...])
 4 APPPATH\Controllers\influencer_controller.php(34): App\Models\database24_->query_24(null, null)
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-13 02:18:28 --> Undefined property: stdClass::$view
in APPPATH\Libraries\post.php on line 45.
 1 APPPATH\Libraries\post.php(45): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: stdClass::$view', 'APPPATH\\Libraries\\post.php', 45, [...])
 2 APPPATH\Controllers\influencer_controller.php(46): App\Libraries\post->postt('284227', 'facebook')
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-13 02:18:52 --> Undefined property: stdClass::$createddate_post
in APPPATH\Libraries\post.php on line 46.
 1 APPPATH\Libraries\post.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: stdClass::$createddate_post', 'APPPATH\\Libraries\\post.php', 46, [...])
 2 APPPATH\Controllers\influencer_controller.php(46): App\Libraries\post->postt('284227', 'facebook')
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-13 02:28:35 --> Cannot use object of type App\Libraries\Link as array
in APPPATH\Libraries\link.php on line 56.
 1 APPPATH\Controllers\influencer_controller.php(43): App\Libraries\Link->link('11081', 'instagram')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-13 02:54:12 --> Undefined index: network
in APPPATH\Views\view.php on line 19.
 1 APPPATH\Views\view.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: network', 'APPPATH\\Views\\view.php', 19, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\view.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('view', [], true)
 5 APPPATH\Controllers\influencer_controller.php(67): view('view', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-13 03:37:20 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 in C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('122.155.166.63', 'intern', 'TVIw3yZchDLH', 'influencer', 3306, '', 0)
#1 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Project\system\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,...')
#4 C:\xampp\htdocs\Project\app\Models\database63_.php(20): CodeIgniter\Model->__call('query', Array)
#5 C:\xampp\htdocs\Project\app\Controllers\influencer_controller.php(33): App\Models\database63_->query_63('11081', 'tiktok')
#6 C:\xampp\htdocs\Project\system\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
#7 C:\xampp\htdocs\Project\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
#8 C:\xampp\htdocs\Project\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Project\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 in C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Project\system\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,...')
#3 C:\xampp\htdocs\Project\app\Models\database63_.php(20): CodeIgniter\Model->__call('query', Array)
#4 C:\xampp\htdocs\Project\app\Controllers\influencer_controller.php(33): App\Models\database63_->query_63('11081', 'tiktok')
#5 C:\xampp\htdocs\Project\system\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
#6 C:\xampp\htdocs\Project\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
#7 C:\xampp\htdocs\Project\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Project\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-13 03:37:20 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,follower,post_total FROM influencer_stat_post_recent WHERE network = \'tiktok\' AND influencer_id = \'11081\'
        ORDER BY create_date DESC
        LIMIT 0,1')
 3 APPPATH\Models\database63_.php(20): CodeIgniter\Model->__call('query', [...])
 4 APPPATH\Controllers\influencer_controller.php(33): App\Models\database63_->query_63('11081', 'tiktok')
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-13 03:37:31 --> Error connecting to the database: mysqli_sql_exception: An established connection was aborted by the software in your host machine.
 in C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('122.155.166.63', 'intern', 'TVIw3yZchDLH', 'influencer', 3306, '', 0)
#1 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Project\system\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,...')
#4 C:\xampp\htdocs\Project\app\Models\database63_.php(20): CodeIgniter\Model->__call('query', Array)
#5 C:\xampp\htdocs\Project\app\Controllers\influencer_controller.php(33): App\Models\database63_->query_63(NULL, NULL)
#6 C:\xampp\htdocs\Project\system\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
#7 C:\xampp\htdocs\Project\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
#8 C:\xampp\htdocs\Project\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Project\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: An established connection was aborted by the software in your host machine.
 in C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Project\system\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,...')
#3 C:\xampp\htdocs\Project\app\Models\database63_.php(20): CodeIgniter\Model->__call('query', Array)
#4 C:\xampp\htdocs\Project\app\Controllers\influencer_controller.php(33): App\Models\database63_->query_63(NULL, NULL)
#5 C:\xampp\htdocs\Project\system\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
#6 C:\xampp\htdocs\Project\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
#7 C:\xampp\htdocs\Project\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Project\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-13 03:37:31 --> Unable to connect to the database.
Main connection [MySQLi]: An established connection was aborted by the software in your host machine.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,follower,post_total FROM influencer_stat_post_recent WHERE network = \'\' AND influencer_id = \'\'
        ORDER BY create_date DESC
        LIMIT 0,1')
 3 APPPATH\Models\database63_.php(20): CodeIgniter\Model->__call('query', [...])
 4 APPPATH\Controllers\influencer_controller.php(33): App\Models\database63_->query_63(null, null)
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-13 03:48:01 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 in C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('122.155.166.63', 'intern', 'TVIw3yZchDLH', 'influencer', 3306, '', 0)
#1 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Project\system\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,...')
#4 C:\xampp\htdocs\Project\app\Models\database63_.php(20): CodeIgniter\Model->__call('query', Array)
#5 C:\xampp\htdocs\Project\app\Controllers\influencer_controller.php(33): App\Models\database63_->query_63('11081', 'tiktok')
#6 C:\xampp\htdocs\Project\system\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
#7 C:\xampp\htdocs\Project\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
#8 C:\xampp\htdocs\Project\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Project\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 in C:\xampp\htdocs\Project\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Project\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Project\system\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,...')
#3 C:\xampp\htdocs\Project\app\Models\database63_.php(20): CodeIgniter\Model->__call('query', Array)
#4 C:\xampp\htdocs\Project\app\Controllers\influencer_controller.php(33): App\Models\database63_->query_63('11081', 'tiktok')
#5 C:\xampp\htdocs\Project\system\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
#6 C:\xampp\htdocs\Project\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
#7 C:\xampp\htdocs\Project\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Project\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-13 03:48:01 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Model.php(768): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,follower,post_total FROM influencer_stat_post_recent WHERE network = \'tiktok\' AND influencer_id = \'11081\'
        ORDER BY create_date DESC
        LIMIT 0,1')
 3 APPPATH\Models\database63_.php(20): CodeIgniter\Model->__call('query', [...])
 4 APPPATH\Controllers\influencer_controller.php(33): App\Models\database63_->query_63('11081', 'tiktok')
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
